import bcrypt from "bcrypt";
import { randomBytes, timingSafeEqual } from "node:crypto";
import { createRemoteJWKSet, importPKCS8, jwtVerify, SignJWT } from "jose";
import { OAuthProvider } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";
export type OAuthProviderName = "google" | "apple" | "facebook";
type Profile = { providerAccountId: string; email: string | null; name: string };
const appUrl = (process.env.APP_URL ?? "http://localhost:3000").replace(/\/$/, "");
const callback = (p: OAuthProviderName) => `${appUrl}/api/auth/oauth/${p}/callback`;
const map: Record<OAuthProviderName, OAuthProvider> = { google: OAuthProvider.GOOGLE, apple: OAuthProvider.APPLE, facebook: OAuthProvider.FACEBOOK };
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; };
export const isProvider = (value: string): value is OAuthProviderName => value === "google" || value === "apple" || value === "facebook";
export const createOAuthState = () => randomBytes(32).toString("base64url");
export const stateMatches = (expected: string | undefined, received: string | null) => { if (!expected || !received) return false; const a = Buffer.from(expected); const b = Buffer.from(received); return a.length === b.length && timingSafeEqual(a, b); };
export function authorizationUrl(provider: OAuthProviderName, state: string) { const url = new URL(provider === "google" ? "https://accounts.google.com/o/oauth2/v2/auth" : provider === "apple" ? "https://appleid.apple.com/auth/authorize" : "https://www.facebook.com/v21.0/dialog/oauth"); url.searchParams.set("client_id", required(provider === "google" ? "GOOGLE_CLIENT_ID" : provider === "apple" ? "APPLE_CLIENT_ID" : "FACEBOOK_CLIENT_ID")); url.searchParams.set("redirect_uri", callback(provider)); url.searchParams.set("response_type", "code"); url.searchParams.set("state", state); if (provider === "google") url.searchParams.set("scope", "openid email profile"); if (provider === "apple") { url.searchParams.set("scope", "name email"); url.searchParams.set("response_mode", "form_post"); } if (provider === "facebook") url.searchParams.set("scope", "email,public_profile"); return url.toString(); }
async function appleSecret() { const key = await importPKCS8(required("APPLE_PRIVATE_KEY").replace(/\\n/g, "\n"), "ES256"); return new SignJWT({}).setProtectedHeader({ alg: "ES256", kid: required("APPLE_KEY_ID") }).setIssuer(required("APPLE_TEAM_ID")).setSubject(required("APPLE_CLIENT_ID")).setAudience("https://appleid.apple.com").setIssuedAt().setExpirationTime("180d").sign(key); }
export async function getOAuthProfile(provider: OAuthProviderName, code: string, appleUser: string | null): Promise<Profile> { const clientId = required(provider === "google" ? "GOOGLE_CLIENT_ID" : provider === "apple" ? "APPLE_CLIENT_ID" : "FACEBOOK_CLIENT_ID"); const secret = provider === "google" ? required("GOOGLE_CLIENT_SECRET") : provider === "apple" ? await appleSecret() : required("FACEBOOK_CLIENT_SECRET"); const endpoint = provider === "google" ? "https://oauth2.googleapis.com/token" : provider === "apple" ? "https://appleid.apple.com/auth/token" : "https://graph.facebook.com/v21.0/oauth/access_token"; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: clientId, client_secret: secret, redirect_uri: callback(provider), grant_type: "authorization_code" }) }); const token = await response.json() as { access_token?: string; id_token?: string; error?: string }; if (!response.ok || !token.access_token) throw new Error(token.error ?? "OAuth token exchange failed."); if (provider === "google") { const r = await fetch("https://openidconnect.googleapis.com/v1/userinfo", { headers: { Authorization: `Bearer ${token.access_token}` } }); const p = await r.json() as { sub?: string; email?: string; email_verified?: boolean; name?: string }; if (!r.ok || !p.sub || !p.email || !p.email_verified) throw new Error("Google did not provide a verified email."); return { providerAccountId: p.sub, email: p.email.toLowerCase(), name: p.name ?? p.email }; } if (provider === "facebook") { const r = await fetch(`https://graph.facebook.com/me?fields=id,name,email&access_token=${encodeURIComponent(token.access_token)}`); const p = await r.json() as { id?: string; email?: string; name?: string }; if (!r.ok || !p.id || !p.email) throw new Error("Facebook did not provide an email address."); return { providerAccountId: p.id, email: p.email.toLowerCase(), name: p.name ?? p.email }; } if (!token.id_token) throw new Error("Apple did not provide an identity token."); const { payload } = await jwtVerify(token.id_token, createRemoteJWKSet(new URL("https://appleid.apple.com/auth/keys")), { issuer: "https://appleid.apple.com", audience: clientId }); const email = typeof payload.email === "string" ? payload.email.toLowerCase() : null; if (!payload.sub) throw new Error("Apple did not provide an account identifier."); const user = appleUser ? JSON.parse(appleUser) as { name?: { firstName?: string; lastName?: string } } : undefined; return { providerAccountId: payload.sub, email, name: [user?.name?.firstName, user?.name?.lastName].filter(Boolean).join(" ") || email || "Apple user" }; }
export async function findOrCreateOAuthUser(provider: OAuthProviderName, profile: Profile) { const account = await prisma.oAuthAccount.findUnique({ where: { provider_providerAccountId: { provider: map[provider], providerAccountId: profile.providerAccountId } }, include: { user: true } }); if (account) return account.user; if (!profile.email) throw new Error("Apple did not provide an email address for this new account."); const email = profile.email; const password = await bcrypt.hash(randomBytes(32).toString("hex"), 12); return prisma.$transaction(async (tx) => { const existing = await tx.user.findUnique({ where: { email } }); const user = existing ?? await tx.user.create({ data: { email, name: profile.name, password, emailVerifiedAt: new Date() } }); await tx.oAuthAccount.create({ data: { provider: map[provider], providerAccountId: profile.providerAccountId, userId: user.id } }); return user; }); }
