import { GraduationCap, Trash2 } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { createTeacher, deleteTeacher, updateTeacher } from "./actions";

export default async function TeachersPage() {
  const teachers = await prisma.instructor.findMany({ include: { _count: { select: { courses: { where: { deletedAt: null } } } } }, orderBy: { name: "asc" } });

  return <div className="space-y-8"><div><p className="text-sm text-foreground-subtle">Команда школы</p><h1 className="mt-1 font-serif text-4xl">Преподаватели</h1><p className="mt-3 text-foreground-muted">Добавляйте новых преподавателей — они сразу появятся в форме создания курса.</p></div><section className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Новый преподаватель</h2><form action={createTeacher} className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><input required name="name" placeholder="Имя и фамилия" className="rounded-lg border border-border p-3" /><input name="bio" placeholder="Коротко о преподавателе" className="rounded-lg border border-border p-3" /><button className="rounded-lg bg-accent px-4 py-3 text-sm text-white">Добавить</button></form></section><section className="grid gap-4">{teachers.map((teacher) => <article key={teacher.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-background text-accent"><GraduationCap className="h-5 w-5" /></div><form action={updateTeacher.bind(null, teacher.id)} className="grid flex-1 gap-3 md:grid-cols-[1fr_2fr_auto]"><input required name="name" defaultValue={teacher.name} className="rounded-lg border border-border p-3" /><input name="bio" defaultValue={teacher.bio ?? ""} placeholder="Коротко о преподавателе" className="rounded-lg border border-border p-3" /><button className="rounded-lg border border-border px-4 py-3 text-sm">Сохранить</button></form></div><div className="mt-4 flex items-center justify-between border-t border-border pt-4"><p className="text-sm text-foreground-muted">Активных курсов: {teacher._count.courses}</p>{teacher._count.courses === 0 ? <form action={deleteTeacher.bind(null, teacher.id)}><button className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-700 hover:bg-red-50"><Trash2 className="h-4 w-4" />Удалить</button></form> : <p className="text-xs text-foreground-subtle">Сначала переназначьте курсы, чтобы удалить</p>}</div></article>)}</section></div>;
}
