import { AdminSubmitButton } from "@/components/admin/AdminSubmitButton";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createVideo, deleteVideo, moveVideo, updateModule, updateVideo } from "./actions";
import { ImageUploadField } from "@/components/admin/ImageUploadField";

export default async function ModulePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const courseModule = await prisma.module.findUnique({ where: { id }, include: { videos: { where: { deletedAt: null }, orderBy: { order: "asc" } } } });
  if (!courseModule) notFound();

  return <div className="space-y-8 px-4 sm:px-6 lg:px-12 xl:px-20 py-6  md:py-10"><Link href={`/admin/courses/${courseModule.courseId}/content`} className="text-sm text-accent underline">← Back to course content</Link><div><p className="text-sm text-foreground-subtle">Module {courseModule.order}</p><h1 className="mt-1 font-serif text-3xl font-bold">{courseModule.title}</h1></div>
    <form action={updateModule.bind(null, courseModule.id, courseModule.courseId)} className="grid gap-3 rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-semibold">Edit module</h2><input required name="title" defaultValue={courseModule.title} className="rounded border border-border bg-background p-3" /><textarea name="description" defaultValue={courseModule.description ?? ""} className="min-h-24 rounded border border-border bg-background p-3" /><ImageUploadField name="previewImage" defaultValue={courseModule.previewImage} label="Module thumbnail" /><div className="grid gap-3 sm:grid-cols-2"><input required name="price" type="number" min="0" defaultValue={courseModule.price} className="rounded border border-border bg-background p-3" /><input name="oldPrice" type="number" min="0" defaultValue={courseModule.oldPrice ?? ""} placeholder="Old price (optional)" className="rounded border border-border bg-background p-3" /></div><AdminSubmitButton pendingLabel="Saving…" className="min-h-11 w-fit rounded bg-accent px-4 py-2 text-white">Save module</AdminSubmitButton></form>
    <section><h2 className="font-serif text-2xl font-semibold">Lessons</h2><form action={createVideo.bind(null, courseModule.id, courseModule.courseId)} className="mt-5 grid gap-3 rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">Add lesson</h3><input name="title" placeholder="Lesson title" required className="rounded border border-border bg-background p-3" /><textarea name="description" placeholder="Description" className="min-h-20 rounded border border-border bg-background p-3" /><input name="storageKey" placeholder="Cloudflare key or local video path" required className="rounded border border-border bg-background p-3" /><ImageUploadField name="previewImage" label="Lesson thumbnail" /><div className="grid gap-3 sm:grid-cols-3"><input name="duration" type="number" min="0" placeholder="Duration in seconds" required className="rounded border border-border bg-background p-3" /><input name="price" type="number" min="0" placeholder="Price" required className="rounded border border-border bg-background p-3" /><input name="oldPrice" type="number" min="0" placeholder="Old price (optional)" className="rounded border border-border bg-background p-3" /></div><label className="flex items-center gap-2 text-sm"><input name="isFreePreview" type="checkbox" /> Free preview</label><AdminSubmitButton pendingLabel="Adding…" className="min-h-11 w-fit rounded bg-accent px-4 py-2 text-white">Add lesson</AdminSubmitButton></form>
      <div className="mt-5 space-y-4">{courseModule.videos.length === 0 ? <p className="rounded-xl border border-dashed border-border p-6 text-center text-foreground-muted">No lessons yet.</p> : courseModule.videos.map((video, index) => <form key={video.id} action={updateVideo.bind(null, video.id, courseModule.id, courseModule.courseId)} className="grid gap-3 rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-foreground-subtle">Lesson {video.order}</p><h3 className="font-semibold">{video.title}</h3></div><div className="flex gap-1"><AdminSubmitButton pendingLabel="…" formAction={moveVideo.bind(null, video.id, courseModule.id, courseModule.courseId, "up")} disabled={index === 0} className="min-h-11 min-w-11 rounded border border-border px-3 py-2 disabled:opacity-30">↑</AdminSubmitButton><AdminSubmitButton pendingLabel="…" formAction={moveVideo.bind(null, video.id, courseModule.id, courseModule.courseId, "down")} disabled={index === courseModule.videos.length - 1} className="min-h-11 min-w-11 rounded border border-border px-3 py-2 disabled:opacity-30">↓</AdminSubmitButton></div></div><input name="title" defaultValue={video.title} required className="rounded border border-border bg-background p-3" /><textarea name="description" defaultValue={video.description ?? ""} className="min-h-20 rounded border border-border bg-background p-3" /><input name="storageKey" defaultValue={video.storageKey} required className="rounded border border-border bg-background p-3" /><ImageUploadField name="previewImage" defaultValue={video.previewImage} label="Lesson thumbnail" /><div className="grid gap-3 sm:grid-cols-3"><input name="duration" type="number" min="0" defaultValue={video.duration} required className="rounded border border-border bg-background p-3" /><input name="price" type="number" min="0" defaultValue={video.price} required className="rounded border border-border bg-background p-3" /><input name="oldPrice" type="number" min="0" defaultValue={video.oldPrice ?? ""} placeholder="Old price (optional)" className="rounded border border-border bg-background p-3" /></div><label className="flex items-center gap-2 text-sm"><input name="isFreePreview" type="checkbox" defaultChecked={video.isFreePreview} /> Free preview</label><div className="flex flex-wrap gap-3"><AdminSubmitButton pendingLabel="Saving…" className="min-h-11 rounded bg-accent px-4 py-2 text-white">Save lesson</AdminSubmitButton><Link href={`/admin/videos/${video.id}/practice`} className="inline-flex min-h-11 items-center rounded border border-border px-4 py-2">Practice tasks</Link><AdminSubmitButton pendingLabel="Deleting…" formAction={deleteVideo.bind(null, video.id, courseModule.id, courseModule.courseId)} className="min-h-11 rounded border border-red-600 px-4 py-2 text-red-600">Delete</AdminSubmitButton></div></form>)}</div>
    </section>
  </div>;
}
