ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'FLASHCARD';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'WORD_ORDER';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'LISTENING';

ALTER TABLE "Question" ADD COLUMN "audioUrl" TEXT;
