"use client";

import type { Category, Instructor } from "@/generated/prisma/client";
import { createCourse } from "./actions";

export default function CreateCourse({ instructors, categories }: { instructors: Instructor[]; categories: Category[] }) {
  const disabled = instructors.length === 0 || categories.length === 0;
  return <form action={createCourse} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm">Название<input required name="title" placeholder="Например, Английская грамматика: старт" className="mt-1 w-full rounded-lg border border-border p-3" /></label><label className="text-sm">Стоимость, ₸<input required min="0" name="price" placeholder="29990" type="number" className="mt-1 w-full rounded-lg border border-border p-3" /></label><label className="text-sm md:col-span-2">Описание<textarea required name="description" placeholder="Для кого курс и чему научится ученик" className="mt-1 min-h-24 w-full rounded-lg border border-border p-3" /></label><label className="text-sm">Преподаватель<select required name="instructorId" className="mt-1 w-full rounded-lg border border-border bg-white p-3">{instructors.map((instructor) => <option key={instructor.id} value={instructor.id}>{instructor.name}</option>)}</select></label><label className="text-sm">Категория<select required name="categoryId" className="mt-1 w-full rounded-lg border border-border bg-white p-3">{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm">Уровень<select name="difficulty" className="mt-1 w-full rounded-lg border border-border bg-white p-3"><option value="BEGINNER">Начинающий</option><option value="ELEMENTARY">Базовый</option><option value="INTERMEDIATE">Средний</option><option value="UPPER_INTERMEDIATE">Выше среднего</option><option value="ADVANCED">Продвинутый</option></select></label><label className="text-sm">Статус<select name="status" className="mt-1 w-full rounded-lg border border-border bg-white p-3"><option value="DRAFT">Черновик</option><option value="PUBLISHED">Опубликовать</option></select></label><button disabled={disabled} className="w-fit rounded-lg bg-accent px-5 py-3 text-sm text-white disabled:opacity-50">Создать курс</button>{disabled && <p className="self-center text-sm text-red-700">Сначала добавьте преподавателя и категорию в базу данных.</p>}</form>;
}
